const TOTAL=40,SECONDS=3*60*60,EXAM='d01_2025';
const KEY='ACACACCBCBABABBBCABCBAABACBCABBAACBAABBC';
const API='https://script.google.com/macros/s/AKfycbwtRGWJPNc8n413pPLvQE5ntBUFfJeG2qKJVxhhNG9CM8tlxqXb-j07anfudEV7Zz0y/exec';
const STORE='pne_2025_d01_attempt_v1',$=id=>document.getElementById(id);
let answers=Array(TOTAL).fill(null),index=0,attemptId='',ticket='',student=null,endsAt=0,finished=false,timedOut=false,submitted=false,sending=false,available=false,ticker;
const area=n=>n<=12?'Geometría':n<=35?'Relaciones y Álgebra':'Estadística y Probabilidad';
const context=n=>n>=13&&n<=15?13:n>=36&&n<=38?36:null;
function save(){try{localStorage.setItem(STORE,JSON.stringify({answers,index,attemptId,ticket,student,endsAt,finished,timedOut,submitted}))}catch{}}
function restore(){try{const s=JSON.parse(localStorage.getItem(STORE)||'null');if(!s)return;answers=Array.from({length:TOTAL},(_,i)=>'ABC'.includes(s.answers?.[i])?s.answers[i]:null);index=Math.max(0,Math.min(TOTAL-1,Number(s.index)||0));attemptId=s.attemptId||'';ticket=s.ticket||'';student=s.student||null;endsAt=Number(s.endsAt)||0;finished=!!s.finished;timedOut=!!s.timedOut;submitted=!!s.submitted}catch{}}
function uuid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>(Math.random()*16|0).toString(16))}
function jsonp(op,extra={}){return new Promise((resolve,reject)=>{const callback='examStatus_'+Math.random().toString(36).slice(2),script=document.createElement('script'),url=new URL(API);let timeout;const clean=()=>{clearTimeout(timeout);delete window[callback];script.remove()};window[callback]=data=>{clean();resolve(data)};script.onerror=()=>{clean();reject(Error('No se pudo conectar con el horario.'))};timeout=setTimeout(()=>{clean();reject(Error('La consulta tardó demasiado.'))},12000);Object.entries({op,exam:EXAM,callback,...extra,_:Date.now()}).forEach(([key,value])=>url.searchParams.set(key,value));script.src=url;document.head.append(script)})}
async function check(){available=false;$('start').disabled=true;$('retry').hidden=true;$('availability').textContent='Consultando disponibilidad de la prueba…';try{const status=await jsonp('status');available=!!status.open;$('availability').textContent=status.open?`Prueba disponible${status.endsAt?' hasta '+status.endsAt+' (Costa Rica)':''}.`:status.message||'La prueba está cerrada.';$('start').disabled=!available}catch(e){$('availability').textContent=e.message;$('retry').hidden=false}}
function count(){const n=answers.filter(Boolean).length;$('counter').textContent=`${n} / ${TOTAL} respondidas`;return n}
function show(n){index=n;const id=n+1,c=context(id);$('qtitle').textContent=`Ítem ${id} de ${TOTAL}`;$('area').textContent=area(id);$('qstatus').textContent=answers[n]?`Respuesta: ${answers[n]}`:'Sin responder';$('questionImage').src=`${String(id).padStart(2,'0')}.png`;$('questionImage').alt=`Ítem ${id} del documento original, con sus representaciones y opciones A, B y C`;$('context').hidden=!c;if(c)$('contextImage').src=`context-${c}.png`;document.querySelectorAll('input[name="answer"]').forEach(r=>r.checked=r.value===answers[n]);$('prev').disabled=n===0;$('next').textContent=n===TOTAL-1?'Ir a finalizar':'Siguiente →';const grid=$('grid');grid.replaceChildren();answers.forEach((answer,i)=>{const b=document.createElement('button');b.type='button';b.textContent=i+1;b.className=(answer?'answered ':'')+(i===n?'current':'');b.setAttribute('aria-label',`Ir al ítem ${i+1}${answer?', respondido':''}`);b.onclick=()=>show(i);grid.append(b)});count();save()}
function format(t){const h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=t%60;return[h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}
function clock(){const remaining=Math.max(0,Math.ceil((endsAt-Date.now())/1000));$('clock').textContent=format(remaining);if(!remaining&&!finished)finish(true)}
function enter(){if(!attemptId||!ticket)return;$('welcome').hidden=true;$('results').hidden=true;$('exam').hidden=false;show(index);clock();clearInterval(ticker);ticker=setInterval(clock,1000)}
async function start(){const firstName=$('firstName').value.trim().replace(/\s+/g,' '),lastName=$('lastName').value.trim().replace(/\s+/g,' '),valid=/^[A-Za-zÁÉÍÓÚÜÑáéíóúüñÀ-ÿ' .-]{2,70}$/;if(!valid.test(firstName)||!valid.test(lastName)){$('availability').textContent='Escribe tu nombre y tus apellidos.';return}if(!available){await check();if(!available)return}$('start').disabled=true;$('availability').textContent='Confirmando horario de inicio…';try{const attempt=uuid(),status=await jsonp('start',{id:attempt});if(!status.open||!status.ticket)throw Error(status.message||'La prueba no está disponible.');student={firstName,lastName};attemptId=attempt;ticket=status.ticket;endsAt=Number(status.attemptEndsAtEpoch)||0;if(endsAt<=Date.now())throw Error('El horario de la prueba terminó.');save();enter()}catch(e){$('availability').textContent=e.message;await check()}}
function grade(){const correct=answers.filter((a,i)=>a===KEY[i]).length,blank=answers.filter(a=>!a).length;$('score').textContent=`${correct} / ${TOTAL}`;$('scorePercent').textContent=`${(100*correct/TOTAL).toFixed(1)} % de respuestas correctas${timedOut?' · Tiempo agotado':''}`;$('correct').textContent=correct;$('wrong').textContent=TOTAL-correct-blank;$('blank').textContent=blank;const chart=$('areaCharts');chart.replaceChildren();for(const [label,first,last] of [['Geometría',1,12],['Relaciones y Álgebra',13,35],['Estadística y Probabilidad',36,40]]){let c=0,w=0,b=0;for(let i=first-1;i<last;i++){if(answers[i]===KEY[i])c++;else if(answers[i])w++;else b++}let total=last-first+1,pct=100*c/total;const card=document.createElement('article'),heading=document.createElement('h3'),pie=document.createElement('div'),rate=document.createElement('div'),legend=document.createElement('div');card.className='chart';heading.textContent=label;pie.className='pie';pie.style.setProperty('--c',pct+'%');pie.style.setProperty('--w',100*(c+w)/total+'%');pie.setAttribute('role','img');pie.setAttribute('aria-label',`${label}: ${c} correctas, ${w} incorrectas, ${b} sin responder, de ${total} ítems`);rate.className='rate';rate.textContent=pct.toFixed(1)+' %';legend.className='legend';legend.textContent=`Correctas ${c} · Incorrectas ${w} · Sin responder ${b}`;card.append(heading,pie,rate,legend);chart.append(card)}const review=$('review');review.replaceChildren();answers.forEach((answer,i)=>{const row=document.createElement('div'),label=document.createElement('b'),detail=document.createElement('span');label.textContent=`Ítem ${i+1} · ${area(i+1)}`;detail.textContent=`Tu respuesta: ${answer||'—'} · Correcta: ${KEY[i]}`;detail.className=answer===KEY[i]?'ok':'bad';row.append(label,detail);review.append(row)})}
function result(){clearInterval(ticker);$('welcome').hidden=true;$('exam').hidden=true;$('results').hidden=false;$('clock').textContent='00:00:00';grade();window.scrollTo(0,0)}
function finish(auto=false){$('finishDialog').close();if(finished){result();return}if(!auto){$('finishMessage').textContent=`Has respondido ${count()} de ${TOTAL} ítems. ¿Quieres entregar ahora?`;$('finishDialog').showModal();return}clearInterval(ticker);finished=true;timedOut=endsAt<=Date.now();save();result();send()}
function send(){if(submitted||sending||!ticket)return;sending=true;$('delivery').textContent='Enviando respuestas al registro privado…';$('retryDelivery').hidden=true;const nonce=uuid(),frame=document.createElement('iframe'),form=document.createElement('form');frame.name='upload_'+nonce.replace(/-/g,'');frame.hidden=true;form.hidden=true;form.method='POST';form.action=API;form.target=frame.name;const payload={attemptId,ticket,sessionId:'',firstName:student.firstName,lastName:student.lastName,answers,elapsedSeconds:SECONDS-Math.max(0,(endsAt-Date.now())/1000),timedOut};for(const [name,value] of Object.entries({exam:EXAM,nonce,payload:JSON.stringify(payload)})){const input=document.createElement('input');input.name=name;input.value=value;form.append(input)}document.body.append(frame,form);let timeout;const done=(message,retry)=>{clearTimeout(timeout);window.removeEventListener('message',onMessage);form.remove();frame.remove();sending=false;submitted=!retry;save();$('delivery').textContent=message;$('retryDelivery').hidden=!retry};const onMessage=e=>{if(!/^https:\/\/(?:script\.google\.com|script\.googleusercontent\.com|[a-z0-9-]+[.-]script\.googleusercontent\.com)$/.test(e.origin)||e.data?.kind!=='educacion-abierta-exam-save'||e.data.nonce!==nonce)return;if(e.data.status==='ok'||e.data.status==='duplicate')done('Respuestas recibidas correctamente.',false);else done(e.data.message||'No se pudo guardar el resultado.',true)};window.addEventListener('message',onMessage);timeout=setTimeout(()=>done('No se confirmó la recepción. Pulsa «Reintentar envío».',true),22000);form.submit()}
function reset(){clearInterval(ticker);localStorage.removeItem(STORE);answers=Array(TOTAL).fill(null);index=0;attemptId='';ticket='';student=null;endsAt=0;finished=false;timedOut=false;submitted=false;$('results').hidden=true;$('exam').hidden=true;$('welcome').hidden=false;$('clock').textContent=format(SECONDS);$('firstName').value='';$('lastName').value='';count();check()}
$('start').onclick=start;$('retry').onclick=check;$('retryDelivery').onclick=send;$('restart').onclick=reset;$('prev').onclick=()=>show(Math.max(0,index-1));$('next').onclick=()=>index<TOTAL-1?show(index+1):$('finish').scrollIntoView({behavior:'smooth'});$('finish').onclick=()=>finish(false);$('cancelFinish').onclick=()=>$('finishDialog').close();$('confirmFinish').onclick=()=>{finish(true)};document.querySelectorAll('input[name="answer"]').forEach(r=>r.onchange=()=>{answers[index]=r.value;show(index)});$('zoom').onclick=()=>{const box=$('zoomContent');box.replaceChildren();for(const img of [$('context').hidden?null:$('contextImage'),$('questionImage')].filter(Boolean)){const copy=document.createElement('img');copy.src=img.src;copy.alt=img.alt;box.append(copy)}$('imageDialog').showModal()};$('closeZoom').onclick=()=>$('imageDialog').close();
restore();count();if(finished){result();if(!submitted)$('retryDelivery').hidden=false}else if(attemptId&&ticket){if(endsAt<=Date.now())finish(true);else enter()}else check();
